### ISSUE TITLE
Another Error with latest GitHub release (not 0.9)

### ISSUE THREAD

**Issue by qiangqiang101** [Guad/NativeUI#4]
Sir, another error after update to your latest source code on github
Both your example menu and my menu wasn't show while i press the hotkey

[17:02:00] [DEBUG] Instantiating script 'PremiumDeluxeMotorsport.NET.pdmcarshop' in script domain 'ScriptDomain_E9FE744' ...
[17:02:00] [DEBUG] Started script 'PremiumDeluxeMotorsport.NET.pdmcarshop'.
[17:02:00] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at NativeUI.MenuPool.<>c.<ProcessControl>b__8_0(UIMenu menu)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at NativeUI.MenuPool.ProcessControl()
   at NativeUI.MenuPool.ProcessMenus()
   at PremiumDeluxeMotorsport.NET.pdmcarshop.OnTick(Object o, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()

**Comment by Guad** [comment]
With the latest github version MenuPool is no longer static and you will have to instantiate it.

**Comment by qiangqiang101** [comment]
Thanks problem solved
