### ISSUE TITLE
ScriptHookV.Net 3.0 compatability

### ISSUE THREAD

**Issue by GenesisEB** [Guad/NativeUI#45]
[21:53:42] [ERROR] Failed to instantiate script 'GTA_Realism.Realism' because constructor threw an exception:
System.TypeInitializationException: The type initializer for 'GTA_Realism.Menu' threw an exception. ---> System.MissingMethodException: Method not found: 'Void GTA.Scaleform..ctor(Int32)'.
   at NativeUI.UIMenu..ctor(String title, String subtitle, Point offset, String spriteLibrary, String spriteName)
   at NativeUI.UIMenu..ctor(String title, String subtitle)
   at GTA_Realism.Menu..cctor()
   --- End of inner exception stack trace ---
   at GTA_Realism.Menu.Init()
   at GTA_Realism.Realism..ctor()

**Comment by GenesisEB** [comment]
Just saw the branch, my bad.
